"use client";
import { useState } from 'react';

export default function InserirFilmes() {
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');

  const handleInserirFilmes = async () => {
    setLoading(true);
    const filmes = [
      'Forrest Gump',
      'The Shawshank Redemption',
      'The Matrix',
      'Cidade de Deus',
      'Toy Story',
      'The Godfather',
      'The Dark Knight',
      'Inception',
      'Pulp Fiction',
      'Fight Club',
      'The Shawshank Redemption',
      'Forrest Gump',
      'Gladiator',
      'The Lion King',
      'Titanic',
      'The Lord of the Rings: The Fellowship of the Ring',
      'Interstellar',
      'Back to the Future',
      'The Terminator',
      'Star Wars: A New Hope',
      'The Silence of the Lambs',
      'Schindler’s List',
      'The Avengers',
      'Jaws',
      'Jurassic Park',
      'Saving Private Ryan',
      'Avatar',
      'The Godfather: Part II',
      'City of God',
      'Eternal Sunshine of the Spotless Mind',
      'The Pianist',
      'Goodfellas',
      'The Green Mile',
      'The Prestige',
      'Life is Beautiful',
      'The Wolf of Wall Street',
      '12 Angry Men',
      'The Departed',
      'The Sixth Sense',
      'Parasite',
      'Whiplash',
      'Requiem for a Dream',
      'The Grand Budapest Hotel',
      'American Beauty',
      'Dead Poets Society',
      'A Clockwork Orange',
      'Blade Runner 2049',
      'Mad Max: Fury Road',
      'Django Unchained',
      'The Revenant',
      'The Social Network',
      'Pirates of the Caribbean: The Curse of the Black Pearl',
      'Spider-Man: Into the Spider-Verse',
      'Doctor Strange',
      'The Irishman',
      'Her',
      'Up',
      'Toy Story',
      'Shrek',
      'Inside Out',
      'Finding Nemo',
      'Coco',
      'Frozen',
      'The Incredibles',
      'The Big Lebowski',
      'The Truman Show',
      'Kill Bill: Vol. 1',
      'Kill Bill: Vol. 2',
      'Inglourious Basterds',
      'Casino',
      'The Usual Suspects',
      'Fargo',
      'Mulholland Drive',
      'The Shape of Water',
      'Arrival',
      'The Dark Knight Rises',
      'The Witch',
      'Donnie Darko',
      'The Shining',
      'Get Out',
      'Memento',
      'The Princess Bride',
      'The Notebook',
      'Slumdog Millionaire',
      'Glory',
      'The Pursuit of Happyness',
      'Seven',
      'Black Swan',
      'Moonlight',
      'Bohemian Rhapsody',
      'A Star is Born',
      'The Greatest Showman',
      'Moulin Rouge!',
      'Les Miserables',
      'Sweeney Todd',
      'The Theory of Everything',
      'Lincoln',
      'Hidden Figures',
      'The Imitation Game',
      'Braveheart',
      'The Curious Case of Benjamin Button',
      'Catch Me If You Can',
      'Gone Girl',
      'No Country for Old Men',
      '12 Years a Slave',
      'Dunkirk',
      'The Hurt Locker',
      'Birdman',
      'The Lighthouse',
      'Roma',
      'The Two Popes',
      'Marriage Story',
      'Phantom Thread',
      'The Master',
      'There Will Be Blood',
      'La La Land',
      'Whiplash',
      'The Hateful Eight',
      'The Aviator',
      'The Big Short',
      'Spotlight',
      'The Revenant',
      'Sing Street',
      'A Ghost Story',
      'The Florida Project',
      'The Killing of a Sacred Deer',
      'Lady Bird',
      'The Favourite',
      'Three Billboards Outside Ebbing, Missouri',
      'Coco',
      'Get Out',
      'A Star is Born',
      'Parasite',
      'Jojo Rabbit',
      'Marriage Story',
      'Ford v Ferrari',
      'The Irishman',
      '1917',
      'The Lighthouse',
      'The Farewell',
      'The Joker',
      'Once Upon a Time in America',
      'Blade Runner',
      'Braveheart',
      'Full Metal Jacket',
      'The Big Lebowski',
      'The Departed',
      'Pulp Fiction',
      'Inception',
      'Fight Club',
      'The Prestige',
      'The Matrix',
      'The Godfather Part II',
      'The Silence of the Lambs',
      'The Shawshank Redemption',
      'Goodfellas',
      'Gladiator',
      'Jurassic Park',
      'Saving Private Ryan',
      'Titanic',
      'Avatar',
      'Interstellar',
      'Star Wars: The Empire Strikes Back',
      'The Dark Knight Rises',
      'Jaws',
      'The Lion King',
      'Spider-Man: Homecoming',
      'Frozen II',
      'Wonder Woman',
      'Deadpool',
      'Black Panther',
      'Guardians of the Galaxy',
      'Ant-Man',
      'Doctor Strange',
      'Thor: Ragnarok',
      'Aquaman',
      'Coco',
      'Finding Dory',
      'Toy Story 4',
      'Inside Out',
      'Up',
      'Zootopia',
      'Moana',
      'Wreck-It Ralph',
      'The Lego Movie',
      'Kung Fu Panda',
      'Cloudy with a Chance of Meatballs',
      'How to Train Your Dragon',
      'Shrek',
      'Despicable Me',
      'Megamind',
      'The Secret Life of Pets',
      'The Peanuts Movie',
      'Sing',
      'Trolls',
      'Hotel Transylvania',
      'The Croods',
      'Madagascar',
      'Monsters, Inc.',
      'Cars',
      'Ratatouille',
      'The Incredibles',
      'Finding Nemo',
      'Toy Story',
      'The Lego Movie',
      'Kung Fu Panda',
      'Cloudy with a Chance of Meatballs',
      'How to Train Your Dragon',
      'Zootopia',
      'Moana',
      'Frozen',
      'Trolls',
      'Inside Out',
      'The Secret Life of Pets',
      'The Croods',
      'Despicable Me',
      'The Emoji Movie'
    ];
    

    try {
      const response = await fetch('/api/InserirFilmesExtra', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ titles: filmes }),
      });

      const data = await response.json();
      if (response.ok) {
        setMessage('Filmes inseridos com sucesso!');
      } else {
        setMessage('Erro ao inserir filmes: ' + data.error);
      }
    } catch (error) {
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <h1 className="text-3xl font-bold mb-6">Inserir Filmes da OMDb</h1>
        <button
          onClick={handleInserirFilmes}
          disabled={loading}
          className={`bg-blue-500 text-white px-6 py-3 rounded-lg shadow-lg transition duration-300 ease-in-out transform hover:bg-blue-600 ${loading ? 'opacity-50 cursor-not-allowed' : 'hover:scale-105'}`}
          >
          {loading ? 'Inserindo...' : 'Inserir Filmes'}
        </button>
  {message && <p className="mt-4 text-center text-gray-700">{message}</p>}
</div>

  );
}
